---
title: "Advanced Usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Advanced Usage}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

set.seed(1234)
```

```{r setup}
library(mifa)
```

This is a more complex example. We generate a data set with 5% of the data 
missing completely at random (MCAR):

```{r generate-data, message=FALSE}

library(eigeninv)

e.vals <- c(50, 48, 45, 25, 20, 10, 5, 5, 1, 1, 0.5, 0.5, 0.5, 0.1, 0.1) # eigenvalues
P      <- length(e.vals)  # number of items
N      <- 100             # sample size

# generate a covariance matrix with the eigenvalues in e.vals
cov.mat  <- eigeninv::eiginv(evals = e.vals, symmetric = TRUE) 
chol.cov <- t(chol(cov.mat)) # Cholesky decomposition of the covariance matrix

# Generate centered independent normal data
data.ini1     <- matrix(rnorm(N * P), N, P)
mean.data.ini <- apply(data.ini1, 2, mean)
data.ini      <- t(t(data.ini1) - mean.data.ini)

# generate multivariate normal data with the given covariance matrix.
data <- matrix(0, N, P)
for (i in 1:N) {
  data[i, ] <- chol.cov %*% data.ini[i, ]
}

# Create 5-percent missing data with missing completely at random
data.miss <- data
mcar.n.miss <- 0.05

for (i in 1:P) {
  for (j in 1:N) {
    rand.u <- runif(1)
    if (rand.u <= mcar.n.miss) {
      data.miss[j, i] <- NA
    }
  }
}
```

`mifa.cov()` normally provides the confidence intervals when `ci = TRUE`. 
CIs can also be calculated separately if desired:

```{r run-mifa-ci}

# get imputed covariance using Fieller's method
mi <- mifa(data.miss, m = 10, ci = FALSE)

mifa_ci_fieller(mi$cov_imputations, n_factors = 1:10, N = nrow(data.miss))

# Get CIs using bootstrapping
mifa_ci_boot(data.miss, n_factors = 1:10, n_boot = 100)
```
